### ISSUE TITLE
Undefined function or variable 'mex_vsp'

### ISSUE THREAD

**Issue by moj127** [ahban/VideoSuperpixels#1]
Hi,
I have Matlab R2016a installed on Windows 10. When I run your demo I got this error:
"  Undefined function or variable 'mex_vsp'   "
How should I fix this error? What is mex_vsp here and how can I make it known/defined for Matlab.
Thank you.

**Comment by ahban** [comment]
Hi, @moj127 

Thanks for your interest in our project. I am trying to provide an easy way to compile the code, you will get our source code soon. So that you can compile your own binaries for your platform. 

Best Regards, 
Ban

**Comment by moj127** [comment]
Hi,@ahban 
I really appreciate your efforts and thank you so much.

**Comment by ahban** [comment]
Hi, @moj127 

I suddenly find that the binary mex was not uploaded. I have uploaded it now. Please try the new code.

Regards,
Ban
